services:
  offshore-proxy:
    build:
      context: ./offshore-proxy
    container_name: offshore-proxy
    ports:
      - "9090:8181"
    networks:
      - proxy-network

  ship-proxy:
    build:
      context: ./ship-proxy
    container_name: ship-proxy
    ports:
      - "8080:8080"
    depends_on:
      - offshore-proxy  # Ensure the ship-proxy waits for offshore-proxy to be available
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge